# Project 05 -- Ansh Tandon

**TA Help:** John Smith, Alice Jones

- Help with figuring out how to write a function.
    
**Collaboration:** Friend1, Friend2
    
- Helped figuring out how to load the dataset.
- Helped debug error with my plot.

## Question 1

In [1]:
import pandas as pd

In [2]:
myDF = pd.read_csv("/anvil/projects/tdm/data/noaa/1880.csv" , header=None, names=["id","date","element_code","value","mflag","qflag","sflag","obstime"])

In [3]:
myDF

id      date element_code  value mflag qflag sflag  obstime
0       AGE00147705  18800101         PRCP      0   NaN   NaN     E      NaN
1       AGE00147708  18800101         PRCP     36   NaN   NaN     E      NaN
2       AGE00147709  18800101         PRCP     36   NaN   NaN     E      NaN
3       AGE00147712  18800101         PRCP      0   NaN   NaN     E      NaN
4       AGE00147713  18800101         TMAX     52   NaN   NaN     E      NaN
...             ...       ...          ...    ...   ...   ...   ...      ...
370774  USW00093852  18801231         TMAX     39   NaN   NaN     X      NaN
370775  USW00093852  18801231         TMIN    -17   NaN   NaN     X      NaN
370776  USW00094728  18801231         TMAX   -122   NaN   NaN     0      NaN
370777  USW00094728  18801231         TMIN   -194   NaN   NaN     0      NaN
370778  USW00094728  18801231         PRCP      0   NaN   NaN     0      NaN

[370779 rows x 8 columns]

In [4]:
myDF[(myDF['date'] >= 18800701) & (myDF['date'] <= 18800731)].shape

(31676, 8)

In [5]:
myDF.shape

(370779, 8)

In [6]:
def avg_aggreg_temp(file_location, column_title_list, start_date, end_date, my_element_code = "TAVG"):
    """
    arguments:
    file_location - the exact location in anvil of the specific file to be analyzed
    column_title_list - the names of the columns of the dataset
    start_date - the beginning date to use to analysis
    end_date - the last date to use for analysis
    my_element_code - the type of data (this limits the amount of rows in the data) to be considered in the analysis
    
    returns:
    A float that is the average values of the rows from the start_date to the end_date based upon the element_code parameter passed in
    """
    myDF = pd.read_csv(file_location, header=None, names=column_title_list)
    my_result = myDF[(myDF['date'] >= start_date) & (myDF['date'] <= end_date) & (myDF['element_code'] == my_element_code)]['value'].mean()
    return my_result

In [7]:
avg_aggreg_temp('/anvil/projects/tdm/data/noaa/2018.csv', ["id","date","element_code","value","mflag","qflag","sflag","obstime"], 20180101, 20180115, "TAVG")

12.317542410053962

Markdown notes and sentences and analysis written here.

## Question 2

In [3]:
column_title_list =  ["id","date","element_code","value","mflag","qflag","sflag","obstime"]
myyear = 1880
file_location = f'/anvil/projects/tdm/data/noaa/{myyear}.csv'
my_element_code = 'PCRP'

In [4]:
myresult = myDF[(myDF['element_code'] == my_element_code)]['value'].mean()

In [9]:
def avg_aggreg_temp_by_year(range_of_years, column_title_list, my_element_code = "TAVG") -> float:
    """
    arguments:
    range_of_years - the total amount of years that is inclusive
    column_title_list - the names of the columns of the dataset
    my_element_code  - the type of data (this limits the amount of rows in the data) to be considered in the analysis

    returns:
    a dictionary with one floating point value for each year with the average of the values for the rows corresponding to the chosen elements based on the element_code provided as well
    """
    
    mydict = {}
    for myyear in range_of_years:
        file_location = f'/anvil/projects/tdm/data/noaa/{myyear}.csv'
        myDF = pd.read_csv(file_location, header=None, names=column_title_list)
        myresult = myDF[(myDF['element_code'] == my_element_code)]['value'].mean()
        mydict[myyear] = myresult
    return mydict

In [10]:
avg_aggreg_temp_by_year(range(1880,1884), ["id","date","element_code","value","mflag","qflag","sflag","obstime"], "TAVG")

{1880: 127.30054644808743,
 1881: 49.00669116954104,
 1882: 58.33541290428501,
 1883: 50.54050116550116}

Markdown notes and sentences and analysis written here.

## Question 3

In [7]:
def avg_aggreg_temp_by_year_and_month(range_of_years, mymonth, column_title_list, my_element_code = "TAVG") -> float:
    """
    arguments:
    range_of_years - a list that contains the years of the data we want to analyze
    mymonth - the only month in the range we want to analyze
    column_title_list - the names of the columns of the dataset
    my_element_code  - the type of data (this limits the amount of rows in the data) to be considered in the analysis

    returns:
    a dictionary with one floating point value for each year with the average of the values for the rows corresponding to the chosen elements based on the element_code provided and a specific month
    """
    
    mydict = {}
    for myyear in range_of_years:
        file_location = f'/anvil/projects/tdm/data/noaa/{myyear}.csv'
        myDF = pd.read_csv(file_location, header=None, names=column_title_list)
        myDF['month'] = pd.to_datetime(myDF['date'], format='%Y%m%d').dt.month
        myresult = myDF[(myDF['element_code'] == my_element_code) & (myDF['month'] == mymonth)]['value'].mean()
        mydict[myyear] = myresult
    return mydict

In [8]:
avg_aggreg_temp_by_year_and_month(range(1880,1884), 7,  ["id","date","element_code","value","mflag","qflag","sflag","obstime"], "TAVG")

{1880: 235.09677419354838,
 1881: 200.40793825799338,
 1882: 217.031465093412,
 1883: 212.14209591474244}

Markdown notes and sentences and analysis written here.

## Question 4

In [2]:
def most_qflags(range_of_years, column_title_list, my_qflag) -> dict:
    """
    arguments:
    range_of_years - a list that contains the years of the data we want to analyze
    column_title_list - the names of the columns of the dataset
    my_qflag - the specified type of the qflag based on the paramter passed to the function

    
    returns:
    a dictionary with the list of each of the years in the range provided for the rows corresponding to elements that have the same qflag as provided in the function parameters
    """
    myqflagdict = {}
    for myyear in range_of_years:
        file_location = f'/anvil/projects/tdm/data/noaa/{myyear}.csv'
        myDF = pd.read_csv(file_location, header=None, names=column_title_list)
        qflag = myDF[(myDF['qflag'] == my_qflag)].shape[0]
        mycount = myDF[(myDF['qflag'] == my_qflag)]['value'].count()
        myqflagdict[myyear] = qflag
    return myqflagdict

In [4]:
most_qflags(range(1880, 1884), ["id","date","element_code","value","mflag","qflag","sflag","obstime"], "I") # This gets the years from 1880 to 1883

{1880: 363, 1881: 358, 1882: 397, 1883: 438}

In [5]:
most_qflags(range(1880, 1884), ["id","date","element_code","value","mflag","qflag","sflag","obstime"], "D") # This gets the years from 1880 to 1883

{1880: 548, 1881: 454, 1882: 365, 1883: 214}

In [6]:
most_qflags(range(1880, 1884), ["id","date","element_code","value","mflag","qflag","sflag","obstime"], "X") # This gets the years from 1880 to 1883

{1880: 3, 1881: 14, 1882: 8, 1883: 5}

Therefore, based on the range inputted from 1880 to 1883, I can easily identify the year that has the most qflags for "I", and for that range of years it was 1883.
I tested it with other values as well as shown above.

## Question 5

In [14]:
myDF = pd.read_csv("/anvil/projects/tdm/data/noaa/2022.csv" , header=None, names=["id","date","element_code","value","mflag","qflag","sflag","obstime"])

In [15]:
myDF

id      date element_code  value mflag qflag sflag  obstime
0         AE000041196  20220101         TAVG    204     H   NaN     S      NaN
1         AEM00041194  20220101         TAVG    211     H   NaN     S      NaN
2         AEM00041217  20220101         TAVG    209     H   NaN     S      NaN
3         AEM00041218  20220101         TAVG    207     H   NaN     S      NaN
4         AG000060390  20220101         TAVG    121     H   NaN     S      NaN
...               ...       ...          ...    ...   ...   ...   ...      ...
37786672  WF000917530  20221231         TAVG    283     H   NaN     S      NaN
37786673  WQW00041606  20221231         TAVG    278     H   NaN     S      NaN
37786674  WZ004455110  20221231         TAVG    203     H   NaN     S      NaN
37786675  ZI000067775  20221231         TAVG    206     H   NaN     S      NaN
37786676  ZI000067975  20221231         TAVG    202     H   NaN     S      NaN

[37786677 rows x 8 columns]

In [23]:
def min_temp_for_years(range_of_years, column_title_list) -> float:
    """
    arguments:
    range_of_years - a list that contains the years of the data we want to analyze
    column_title_list - the names of the columns of the dataset

    returns:
    a dictionary with one floating point value for each year with the minimum temperature values
    """
    
    mydict = {}
    for myyear in range_of_years:
        file_location = f'/anvil/projects/tdm/data/noaa/{myyear}.csv'
        myDF = pd.read_csv(file_location, header=None, names=column_title_list)
        myresult = myDF['value'].min()
        mydict[myyear] = myresult
    return mydict

In [24]:
min_temp_for_years(range(2018, 2022), ["id","date","element_code","value","mflag","qflag","sflag","obstime"])

{2018: -1016, 2019: -2537, 2020: -990, 2021: -796}

Based on the above, I was able to find the minimum values for the temperature for each year given the range of the yeras I provided as the input.

## Pledge

By submitting this work I hereby pledge that this is my own, personal work. I've acknowledged in the designated place at the top of this file all sources that I used to complete said work, including but not limited to: online resources, books, and electronic communications. I've noted all collaboration with fellow students and/or TA's. I did not copy or plagiarize another's work.

> As a Boilermaker pursuing academic excellence, I pledge to be honest and true in all that I do. Accountable together – We are Purdue.